### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by allmightyspiff** [mqlight/python-mqlight#1]
I'm having trouble running setup.py to get this library installed.

Here is basically what I'm doing

```
git clone https://github.com/mqlight/python-mqlight.git
cd python-mqlight
python setup.py install
```

This gives me an error 

```
IOError: [Errno 2] No such file or directory: '/domainThing/python-mqlight/description.rst'
```

If I just create an empty file with that name I can get a bit farther.

```
# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to mqlight.egg-info/requires.txt
writing mqlight.egg-info/PKG-INFO
writing top-level names to mqlight.egg-info/top_level.txt
writing dependency_links to mqlight.egg-info/dependency_links.txt
reading manifest file 'mqlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'include'
writing manifest file 'mqlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building '_cproton' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/domainThing/python-mqlight/include -I/usr/include/python2.7 -c mqlight/cproton.c -o build/temp.linux-x86_64-2.7/mqlight/cproton.o
x86_64-linux-gnu-gcc: error: mqlight/cproton.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```

I've installed qpid-proton-0.12, but I don't see a cproton.c file anywhere on my system. Suggestions?

```
#  locate cproton
/usr/lib/python2.7/dist-packages/_cproton.so
/usr/lib/python2.7/dist-packages/cproton.py
/usr/lib/python2.7/dist-packages/cproton.pyc
/usr/lib/python2.7/dist-packages/cproton.pyo
```

Also, if I'm just doing this wrong please let me know (a readme.md file would help too).

Thanks.

**Comment by dnwe** [comment]
@allmightyspiff - thanks for your interest! 

The python-mqlight code here is still an unreleased beta and this repository hasn't yet been opened up beyond being a public cache for readthedocs to build from.

However, you should be able to install from the readthedocs branch (which has pre-built qpid-proton binaries for linux x86_64) by doing:

``` sh
pip install --user https://github.com/mqlight/python-mqlight/archive/readthedocs.tar.gz
```

OR

``` sh
pip install --user git+git://github.com/mqlight/python-mqlight.git@readthedocs
```

(or manually switching to that git branch and running `python setup.py install`)

Any feedback on the client will be gratefully received!

**Comment by allmightyspiff** [comment]
Thanks, that worked out a lot better than what I was trying to do.

I'm getting this error now when I try to use the send.py that was in the samples folder. Have you seen it before?

```
# python send.py  -s "amqps://user:pass@bluemix.net:2906" "THIS IS JUST A TEST AAA"
*** error ***
AttributeError: 'module' object has no attribute 'create_default_context'
Exiting.
```

Previously that command just hung, so that is at least some improvement :)

**Comment by allmightyspiff** [comment]
Never mind, turns out create_default_context was added in python 2.7.9, and Ubuntu ships with 2.7.6 :(
http://stackoverflow.com/questions/28228214/ssl-module-object-has-no-attribute-sslcontext/28228233

Upgrading python fixed it and it looks like everything works now. Thanks :)

**Comment by dnwe** [comment]
Yeah, unfortunately (unlike RHEL) ubuntu haven't backported any of the tls-related security improvements from 2.7.9 to their LTS. We're aligning with Cloudfoundry/Bluemix and requiring a minimum of 2.7.9

**Comment by dnwe** [comment]
I'll mark this issue as fixed, but feel free to come back if you have further questions.

**Comment by AnnaelleCOHEN** [comment]
Hi , 
When I install the thareadcodes and then import mqlight in python script I get the following:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mqlight/**init**.py", line 16, in <module>
    from .client import **version**, Client
  File "mqlight/client.py", line 60, in <module>
    from .mqlproton import _MQLightMessenger, _MQLightMessage, \
  File "mqlight/mqlproton.py", line 22, in <module>
    from . import cproton
  File "mqlight/cproton.py", line 28, in <module>
    _cproton = swig_import_helper()
  File "mqlight/cproton.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cproton', fp, pathname, description)
ImportError: dlopen(mqlight/_cproton.so, 2): Symbol not found: _PN_OBJECT
  Referenced from: mqlight/_cproton.so
  Expected in: flat namespace
 in mqlight/_cproton.so

what should we install?
Many thanks,
