### ISSUE TITLE
Get messages from the queue

### ISSUE THREAD

**Issue by allmightyspiff** [mqlight/python-mqlight#3]
Is it possible to get old messages from MQlight?

For example, if I use examples/send.py to create a message, THEN use examples/recv.py to get items, nothing happens. I can see the message in the dashboard though.

Running recv.py first, then send.py works, but I can't seem to find a way to get that first message from the queue. 

Also, the link to provide feed back in the documentation seems to point to a 404 page :(
https://www.ibm.com/developerworks/community/groups/service/html/communityview/?communityUuid=00a6a6d0-9601-44cb-a2a2-b0b26811790a

If there is a better place to ask these sort of questions, please let me know.

**Comment by mimaison** [comment]
Hi @allmightyspiff,

With the MQLight server there is no way to receive messages that were sent before you subscribed. I agree, seeing the message is the dashboard can be misleading but that was a design decision we made.

You are also correct, the links in our docs are currently broken, you can access the MQLight community using: https://www.ibm.com/developerworks/community/groups/service/html/communityview?communityUuid=00a6a6d0-9601-44cb-a2a2-b0b26811790a

**Comment by dnwe** [comment]
Updated the release notes to use the short url https://ibm.biz/mqlight-forum
