### ISSUE TITLE
MQLight clients not receiving messages on UK Production

### ISSUE THREAD

**Issue by nttnhan** [mqlight/python-mqlight#5]
On  UK Production, MQLight client  is able to send out messages, but not able to receive any message.
I opened RTC [192653](https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/CloudOE#action=com.ibm.team.workitem.viewWorkItem&id=192653) for this

**Comment by dnwe** [comment]
Looks like this issue had been resolved with support. Closing.
